# Generated by Django 5.2 on 2025-04-16 18:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email ID"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="User ID"
            ),
        ),
    ]
